import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
const src = fileURLToPath(new URL("../src/cjk-charset.txt", import.meta.url));
const dst = fileURLToPath(new URL("../src/cjk-charset.ts", import.meta.url));
const data = readFileSync(src, "utf8");
const escaped = data.replace(/[`$\\]/g, (c) => "\\" + c);
writeFileSync(dst, `// GENERATED by scripts/gen-cjk.mjs from cjk-charset.txt. Do not edit by hand.\nexport const CJK_CHARSET = \`${escaped}\`;\n`);
console.log(`wrote ${dst} (${data.length} chars)`);
